// <auto-generated />
using AccesoDatos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20260818210151_AgregaHerenciaEstudianteProfesor")]
    partial class AgregaHerenciaEstudianteProfesor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AccesoDatos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AccesoDatos.Models.Estudiante", b =>
                {
                    b.HasBaseType("AccesoDatos.Models.Usuario");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Promedio")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("AccesoDatos.Models.Profesor", b =>
                {
                    b.HasBaseType("AccesoDatos.Models.Usuario");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sueldo")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Profesor");
                });
#pragma warning restore 612, 618
        }
    }
}
